version: '3'

networks:
  sf_base:

services:
  mysql:
    container_name: sf_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - sf_base
    volumes:
      - ./database/data:/var/lib/mysql
  php:
    container_name: sf_php
    build:
      context: docker/php
    ports:
      - "9000:9000"
    networks:
      - sf_base
    volumes:
      - .:/var/www/symfony
      - /var/wwww/symfony/vendor
  nginx:
    container_name: sf_nginx
    build: docker/nginx
    ports:
      - 80:80
    networks:
      - sf_base
    volumes:
      - .:/var/www/symfony
      - /var/wwww/symfony/vendor
    depends_on:
      - php

